<?php


namespace Application\Controller;


use Recipe\Doctrine\Model\Recipe;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use ZfcUser\Controller\UserController;

class RecipeController extends AbstractActionController
{
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Chankone the autogenerated stub
    }

    public function showAction()
    {

        $id = $this->params('id');
        /**
         * @var RecipeServiceInterface $recipeService
         */
        $recipeService = $this->getServiceLocator()->get(\Recipe\Doctrine\Service\RecipeServiceInterface::class);
        $recipe = $recipeService->findById($id);
        return new ViewModel(array('recipe' => $recipe));

    }

    public function listAction()
    {
        /**
         * @var RecipeServiceInterface $recipeService
         */
        $recipeService = $this->getServiceLocator()->get(\Recipe\Doctrine\Service\RecipeServiceInterface::class);

        return new ViewModel(array('recipes' => $recipeService->findAll()));
    }

    public function createAction()
    {
        if (!$this->zfcUserAuthentication()->hasIdentity()) {
            return $this->redirect()->toRoute(UserController::ROUTE_LOGIN);
        }
        /*
        if(! $this->zfcUserAuthentication()->hasIdentity()) {
            return $this->redirect()->toRoute(UserController::ROUTE_LOGIN
            .'?redirect=' . rawurlencode($this->url(null))
            );
        }*/


        return new ViewModel(array('recipes' => null));

    }
}