<?php


namespace Application\Controller;


use Recipe\Doctrine\Service\UserServiceInterface;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class UserController extends AbstractActionController
{

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function showAction()
    {
        $id = $this->params('id');

        /**
         * @var UserServiceInterface $userService
         */
        $userService = $this->getServiceLocator()->get(\Recipe\Doctrine\Service\UserServiceInterface::class);
        $user = $userService->findById($id);
        return new ViewModel(array('user' => $user));
    }

    public function listAction()
    {
        /**
         * @var UserServiceInterface $userService
         */
        $userService = $this->getServiceLocator()->get(\Recipe\Doctrine\Service\UserServiceInterface::class);

        return new ViewModel(['users' => $userService->findAll()]);
    }
}