<div class="jumbotron">
    <h1>All Users</h1>
</div>
<div class="row">
    <?php foreach ($users as $user): ?>
        <?php /* @var \Recipe\Doctrine\Model\User $user*/?>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="/user/show/<?php echo $user->getId()?>">

                    <div class="caption">
                        <h3><?php echo $user->getDisplayName() ?></h3>

                    </div>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
</div>

