<?php
/**
 * @var \Recipe\Doctrine\Model\User $user
 */

?>
<div class="jumbotron">
    <h1><?php echo $user->getDisplayName() ?></h1>


</div>

<div class="row">

    <?php foreach ($user->getRecipes() as $recipe) : ?>
        <?php
        /**
         * @var \Recipe\Doctrine\Model\Recipe $recipe
         */
        ?>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="/recipe/show/<?php echo $recipe->getId()?>">
                    <img src="<?php echo $this->basePath('img/suppe.jpeg') ?>" alt="...">
                    <div class="caption">
                        <h3><?php echo $recipe->getTitle() ?></h3>
                        <p>Total Time <?php echo $recipe->getTotalTime()?>min. </p>
                        <p>Level <?php echo $recipe->getLevel()?></p>
                    </div>
                </a>
            </div>
        </div>





    <?php endforeach; ?>
</div>
