<div class="jumbotron">
	<h1><?php echo sprintf('Bärlauch%ssuppe%s', '<span class="zf-green">', '</span>') ?></h1>
	<p><?php echo sprintf($this->translate('Schmeckt Lecker')) ?></p>
	<!--
	-->
	<img class="img-responsive" height="10" src="<?php echo $this->basePath('img/suppe.jpeg') ?>"
		 alt="Suppe">
	<p>
	<ul class="list-group">
		<li class="list-group-item">Total Time: ca. 10 Min.</li>
		<li class="list-group-item">Difficult: normal</li>
		<li class="list-group-item">Calories p. P.: n/a</li>
	</ul>
	</p>


</div>

<div class="row">

	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate('Instructions') ?></h3>
			</div>
			<div class="panel-body">
				<p>Die Zwiebel schälen und in einer Pfanne mit der Butter anschwitzen, bis sie goldgelb ist.
					Mit der Brühe aufgießen und Kartoffeln sowie Bärlauch beifügen (dabei vier Blätter Bärlauch für die
					Garnitur zurück behalten). Mit Salz und Pfeffer abschmecken und langsam köcheln lassen, bis die
					Kartoffeln weich sind.
					Dann die Suppe mit einem Pürierstab mischen und zum Schluss die Sahne unterheben.
					Nochmals kurz aufkochen lassen und heiß mit dem Bärlauch garniert servieren.
				</p>
				<p><a class="btn btn-success pull-right"
					  href="http://www.chefkoch.de/rezepte/1344851239268930/Exzellente-Baerlauchsuppe.html"
					  target="_blank"><?php echo $this->translate('Source') ?> &raquo;</a></p>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate('Ingredients') ?></h3>
			</div>
			<div class="panel-body">

				<table class="table table-hover">
					<thead>
					<tr>
						<th>Quantity</th>
						<th>Item</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						<td>100 g</td>
						<td> Bärlauch, frisch</td>
					</tr>

					<tr>
						<td>5</td>
						<td> m.-große Kartoffel(n), geschält und in Stücke geschnitten</td>
					</tr>
					<tr>
						<td>1</td>
						<td>Zwiebel</td>
					</tr>
					<tr>
						<td>1 Liter</td>
						<td>Gemüsebrühe</td>
					</tr>
					<tr>
						<td>50ml</td>
						<td>Sahne</td>
					</tr>
					<tr>
						<td>-</td>
						<td>Salz</td>
					</tr>
					<tr>
						<td>-</td>
						<td>Pfeffer</td>
					</tr>
					<tr>
						<td>2EL</td>
						<td>Butter</td>
					</tr>
					</tbody>
				</table>

			</div>
		</div>
	</div>


</div>
